### ISSUE TITLE
About test 

### ISSUE THREAD

**Issue by SunQiu88** [weihao1115/cat-sam#4]
Hello,thanks for your great work!
I have trained CAT-SAM with my own data, and I want to test the segmentation performance on an unlabelled image. How can I implement the testing script？Additionally, can CAT-SAM use SAM's method to achieve whole-image automatic segmentation?

**Comment by weihao1115** [comment]
Hi @SunQiu88 ,

Thank you for your interest in our work!

> How can I implement the testing script?

Our team is actively developing inference code for CAT-SAM and our related project, MM-SAM. We'll update the repository with inference code for custom datasets as soon as possible. Please stay tuned for these updates.

> Can CAT-SAM use SAM's method to achieve whole-image automatic segmentation?

We haven't specifically tested this functionality. We encourage you to explore this possibility and would be happy to assist if you encounter any issues during your experiments.

If you have any further questions or need additional clarification, please don't hesitate to ask.

Best regards,

**Comment by weihao1115** [comment]
We have updated the inference code for customized model inference. Please check [here](https://github.com/weihao1115/cat-sam?tab=readme-ov-file#inference).

Best regards,

**Comment by msseibel** [comment]
Has there been an update towards automatic mask generation?
Is there a potential conflict with the design of cat-sam and automatic mask generation? I.e. cat-sam has never been trained with a grid of 32x32 points.

I believe this issue is highly relevant and should not be closed until support for SAMs `automatic_mask_generator` is given or unfeasibility has been shown.
